# Generated by Django 3.2.6 on 2021-08-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attr_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Enter company full name', max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('registration_no', models.CharField(help_text='Enter company registration number', max_length=20, unique=True)),
                ('main_address', models.CharField(help_text='Enter company registration address', max_length=250)),
                ('post_address', models.CharField(blank=True, help_text='Enter company postal address', max_length=250, null=True)),
                ('bank_iban', models.CharField(blank=True, help_text='Enter company Bank IBAN number', max_length=100, null=True)),
                ('keyword', models.CharField(blank=True, help_text='Enter company Tildes JUMIS keyword', max_length=50, null=True, unique=True)),
                ('comp_date', models.DateField(blank=True, null=True)),
                ('vat_date', models.DateField(blank=True, null=True)),
                ('mun_period_from', models.DateField(blank=True, null=True)),
                ('mun_period_to', models.DateField(blank=True, null=True)),
                ('nace_code', models.CharField(blank=True, help_text='Enter company NACE code', max_length=20, null=True)),
                ('nace_desc', models.CharField(blank=True, help_text='Enter company NACE description', max_length=100, null=True)),
                ('contr_id', models.CharField(blank=True, help_text='Enter sales contract id if exists', max_length=30, null=True)),
                ('is_not_active', models.BooleanField(default=False)),
                ('comp_form', models.CharField(blank=True, help_text='Enter company status/form', max_length=100, null=True)),
                ('risk_asses_1', models.CharField(blank=True, help_text='2. Darījumu raksturs', max_length=250, null=True)),
                ('risk_asses_2', models.CharField(blank=True, help_text='3. Personīga tikšanās', max_length=250, null=True)),
                ('risk_asses_3', models.CharField(blank=True, help_text='4. Politiski nozīmīga persona', max_length=250, null=True)),
                ('risk_asses_4', models.CharField(blank=True, help_text='5. Vai PLG ir iekļauts sankciju sarakstos?', max_length=250, null=True)),
                ('risk_asses_5', models.CharField(blank=True, help_text='6. PLG rezidences valsts', max_length=250, null=True)),
                ('risk_asses_6', models.CharField(blank=True, help_text='7. Klienta saimnieciskās darbības ilgums', max_length=250, null=True)),
                ('risk_asses_7', models.CharField(blank=True, help_text='8. Cik ilgi pazīstams PLG', max_length=250, null=True)),
                ('risk_asses_8', models.CharField(blank=True, help_text='9. Saimnieciskās darbības risks', max_length=250, null=True)),
                ('risk_asses_9', models.CharField(blank=True, help_text='10. Kādās valstīs notiek pakalpojumu sniegšana', max_length=250, null=True)),
                ('risk_asses_10', models.CharField(blank=True, help_text='11. Informācija par amatpersonām masu medijos', max_length=250, null=True)),
                ('risk_asses_11', models.CharField(blank=True, help_text='NILLTFN riska novērtējums', max_length=50, null=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='attr_related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_comp_name', models.CharField(help_text='Enter related company name', max_length=100)),
                ('rel_comp_reg', models.CharField(blank=True, help_text='Enter company registration number', max_length=20, null=True, unique=True)),
                ('description', models.CharField(default='no description available.', help_text='Enter related company name', max_length=250)),
                ('company', models.ForeignKey(db_column='slug', on_delete=django.db.models.deletion.CASCADE, to='client.attr_company')),
            ],
            options={
                'ordering': ['rel_comp_name'],
            },
        ),
        migrations.CreateModel(
            name='attr_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(help_text='Enter employee full name', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Enter employee role', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter email', max_length=254, null=True)),
                ('tele', models.CharField(blank=True, help_text='Enter employee telephone number', max_length=100, null=True)),
                ('is_board', models.BooleanField(default=False)),
                ('is_sh_holder', models.BooleanField(default=False)),
                ('is_main_benf', models.BooleanField(default=False)),
                ('company', models.ForeignKey(db_column='slug', on_delete=django.db.models.deletion.CASCADE, to='client.attr_company')),
            ],
            options={
                'ordering': ['employee'],
            },
        ),
        migrations.CreateModel(
            name='attr_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(help_text='Enter asset type (e.g car, pc, telephone)', max_length=50)),
                ('asset_id', models.CharField(help_text='Enter asset ID (e.g LV-1009)', max_length=50)),
                ('asset_contr_id', models.CharField(blank=True, help_text='Enter contract id for asset', max_length=50, null=True)),
                ('asset_desc', models.CharField(blank=True, help_text='Enter short description about asset', max_length=250, null=True)),
                ('company', models.ForeignKey(db_column='slug', on_delete=django.db.models.deletion.CASCADE, to='client.attr_company')),
            ],
            options={
                'ordering': ['asset_type'],
            },
        ),
    ]
